version: 2

build:
  os: ubuntu-20.04
  tools:
    python: mambaforge-4.10
  jobs:
    pre_build:
      - doit -n8 dist ||
      - doit dist
      - doit setup
      - doit lite

sphinx:
  builder: html
  configuration: docs/conf.py

conda:
  environment: docs/rtd.yml

formats:
  - htmlzip
  - epub
