dependencies:
  - myst-nb
  - pkginfo
  - pydata-sphinx-theme
  - pytest-check-links
  - sphinx
  - sphinx-autobuild
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - pip:
      - jupyterlite==0.1.0b11
