dependencies:
  - docutils <0.17
  - jupyterlab-webrtc-docprovider
  - myst-nb
  - pkginfo
  - pydata-sphinx-theme
  - pytest-check-links
  - sphinx
  - sphinx-autobuild
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - sphinxext-rediraffe
  - pip:
      - jupyterlite==0.1.0b11
