dependencies:
  - docutils >=0.18
  - jupyterlab-myst
  - myst-nb
  - pkginfo
  - pydata-sphinx-theme
  - pytest-check-links
  - python-graphviz
  - sphinx
  - sphinx-autobuild
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - sphinxext-rediraffe
