dependencies:
  - black
  - docformatter
  - isort
  - mypy
  - pydocstyle
  - pyflakes
  - pylint
  - pyproject-fmt
  - pytest
  - robotframework-robocop
  - robotframework-seleniumlibrary
  - robotframework-tidy
  - ruamel.yaml
  - ssort
  - types-jsonschema
  - types-ujson
