#!/usr/bin/env bash

# some things we just don't need to do on binder
export IN_BINDER=1

set -eux

mamba env update "${NB_PYTHON_PREFIX}" \
    --file ".github/locks/binder-linux-64-3.9/conda.lock"

# do a proper activation
source activate "${NB_PYTHON_PREFIX}"

doit preflight
