#!/usr/bin/env bash

set -eux

mamba create --yes \
    --prefix "${NB_PYTHON_PREFIX}" \
    --file ".github/locks/binder-linux-64-3.9.conda.lock"

# do a proper activation
source activate "${NB_PYTHON_PREFIX}"

# some things we just don't need to do on binder
export DEMO_IN_BINDER=1

jlpm cache clean
rm -rf ${NB_PYTHON_PREFIX}/share/jupyter/lab

doit -n8 preflight docs
