parameters:
  jlpm: jlpm --ignore-optional --prefer-offline --frozen-lockfile
  env_update: conda env update -n jupyterlab-starters --file ci/env-lint.yml --quiet

jobs:
  - job: Lint
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: steps.conda.yml
        parameters:
          name: Linux

      - script: ${{ parameters.env_update }} || ${{ parameters.env_update }} || ${{ parameters.env_update }}
        displayName: update conda environment with test dependencies

      - script: source activate jupyterlab-starters && python scripts/integrity.py
        displayName: check repo integrity

      - script: source activate jupyterlab-starters && python scripts/lint.py
        displayName: lint backend

      - script: git diff || echo "no changes"
        displayName: show changes

      - script: source activate jupyterlab-starters && ${{ parameters.jlpm }} || ${{ parameters.jlpm }} || ${{ parameters.jlpm }}
        displayName: install npm dependencies

      - script: source activate jupyterlab-starters && jlpm build
        displayName: build so linting can complete

      - script: source activate jupyterlab-starters && jlpm lint:check
        displayName: lint frontend
